export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADVERTS_LOADED_SUCCESS = "ADVERTS_LOADED_SUCCESS";
export const ADVERT_LOADED_SUCCESS = "ADVERT_LOADED_SUCCESS";
export const ADVERT_CREATED_SUCCESS = "ADVERT_CREATED_SUCCESS";

export const UI_RESET_ERROR = "UI_RESET_ERROR";
